---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: 'latest'

inputs:
  - name: source
  - name: version

outputs:
  - name: dist

caches:
  - path: .gradle

run:
  path: source/gateway/pipeline/scripts/build.sh
