gateway:
  services:
    videoIngestorUrl: https://video-ingestor.staging-boclips.com
    marketingServiceUrl: https://marketing-service.staging-boclips.com
    userServiceUrl: https://user-service.staging-boclips.com
    videoServiceUrl: https://video-service.staging-boclips.com
    keycloakUrl: https://login.staging-boclips.com
    eventServiceUrl: https://event-service.staging-boclips.com
    orderServiceUrl: https://not-ready-yet.staging-boclips.com
