gateway:
  services:
    videoIngestorUrl: https://video-ingestor.testing-boclips.com
    marketingServiceUrl: https://marketing-service.testing-boclips.com
    userServiceUrl: https://user-service.testing-boclips.com
    videoServiceUrl: https://video-service.testing-boclips.com
    keycloakUrl: https://login.testing-boclips.com
    eventServiceUrl: https://event-service.testing-boclips.com
    orderServiceUrl: https://terry.testing-boclips.com
