spring:
  cloud:
    gateway:
      x-forwarded:
        enabled: false
      forwarded:
        enabled: false
gateway:
  services:
    orderServiceUrl: http://terry
    marketingServiceUrl: http://marketing-service
