spring:
  cloud:
    gateway:
      x-forwarded:
        enabled: false
      forwarded:
        enabled: false
      metrics:
        enabled: false

gateway:
  services:
    orderServiceUrl: http://order-service
    videoIngestorUrl: http://video-ingestor
    userServiceUrl: http://user-service
    eventServiceUrl: http://event-service
    videoServiceUrl: http://video-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics

server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/hal+json,application/xml
