spring:
  cloud:
    gateway:
      x-forwarded:
        enabled: false
      forwarded:
        enabled: false
      metrics:
        enabled: false

gateway:
  services:
    orderServiceUrl: http://terry
    videoIngestorUrl: http://video-ingestor
    userServiceUrl: http://user-service
    eventServiceUrl: http://event-service
    videoServiceUrl: http://video-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
