spring:
  cloud:
    gateway:
      x-forwarded:
        enabled: false
      forwarded:
        enabled: false
gateway:
  services:
    orderServiceUrl: http://terry
    marketingServiceUrl: http://marketing-service
    videoIngestorUrl: http://video-ingestor
    userServiceUrl: http://user-service
    eventServiceUrl: http://event-service
    videoServiceUrl: http://video-service
