gateway:
  services:
    videoIngestorUrl: https://video-ingestor.boclips.com
    marketingServiceUrl: https://marketing-service.boclips.com
    userServiceUrl: https://user-service.boclips.com
    videoServiceUrl: https://video-service.boclips.com
    keycloakUrl: https://login.boclips.com
    eventServiceUrl: https://event-service.boclips.com
