apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  annotations:
    sidecar.jaegertracing.io/inject: jaeger
spec:
  template:
    metadata:
      name: gateway
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: gateway
        image: eu.gcr.io/boclips-prod/boclips/gateway:1
        env:
        - name: SENTRY_RELEASE
          value: gateway-$(VERSION)
        ports:
        - name: http
          containerPort: 5000
        envFrom:
        - secretRef:
            name: gateway
