apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- ingress.yaml
- service.yaml
commonLabels:
  app: gateway
commonAnnotations:
  boclips-version: "0"
patchesStrategicMerge:
- spread-across-zones.yaml
images:
- name: eu.gcr.io/boclips-prod/boclips/gateway
  newTag: "0"
patchesJson6902:
- path: boot-slow.yaml
  target:
    &deployment
    group: apps
    version: v1
    kind: Deployment
    name: gateway
- path: scale-large.yaml
  target: *deployment
vars:
- name: VERSION
  objref:
    kind: Deployment
    name: gateway
    apiVersion: apps/v1
  fieldref:
    fieldpath: metadata.annotations.boclips-version
