apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- ingress.yaml
- service.yaml
commonLabels:
  app: gateway
commonAnnotations:
  boclips-version: "1"
patchesStrategicMerge:
- spread-across-zones.yaml
images:
- name: eu.gcr.io/boclips-prod/boclips/gateway
  newTag: "1"
patchesJson6902:
- path: boot-slow.yaml
  target:
    group: apps
    kind: Deployment
    name: gateway
    version: v1
- path: scale-large.yaml
  target:
    group: apps
    kind: Deployment
    name: gateway
    version: v1
vars:
- fieldref:
    fieldPath: metadata.annotations.boclips-version
  name: VERSION
  objref:
    apiVersion: apps/v1
    kind: Deployment
    name: gateway
