apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
namespace: staging
replicas:
- count: 2
  name: gateway
patches:
- path: domain.yaml
  target:
    group: extensions
    version: v1beta1
    kind: Ingress
- path: jaeger-service-name.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
- path: noncritical.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
